### ISSUE TITLE
datetime.UTC does not work in Python < 3.11

### ISSUE THREAD

**Issue by christopherwharrop-noaa** [ufs-community/uwtools#487]
**Expected behavior**

```
$ uw --version
uw version 2.2.0 build 0
```

**Current behavior**
```
$ uw --version
Traceback (most recent call last):
  File "/path/to/bin/uw", line 10, in <module>
    sys.exit(main())
  File "/path/to/uwtools/cli.py", line 50, in main
    args, checks = _parse_args(sys.argv[1:])
  File "/path/to/uwtools/cli.py", line 1027, in _parse_args
    checks = {k: modes[k]() for k in sorted(modes.keys())}
  File "/path/to/uwtools/cli.py", line 1027, in <dictcomp>
    checks = {k: modes[k]() for k in sorted(modes.keys())}
  File "/path/to/uwtools/cli.py", line 844, in _add_subparser_for_driver
    return {
  File "/path/to/uwtools/cli.py", line 845, in <dictcomp>
    task: _add_subparser_for_driver_task(subparsers, task, helpmsg, with_cycle, with_leadtime)
  File "/path/to/uwtools/cli.py", line 869, in _add_subparser_for_driver_task
    _add_arg_cycle(required)
  File "/path/to/uwtools/cli.py", line 554, in _add_arg_cycle
    offset = dt.timedelta(hours=(dt.datetime.now(dt.UTC).hour // 6) * 6)
AttributeError: module 'datetime' has no attribute 'UTC'
```
**Machines affected**
All

**To Reproduce**
1. Use pip from python < 3.11
2. `pip install 'uwtools @ git+https://github.com/ufs-community/uwtools@main#subdirectory=src'`
3. `uw --version`

**Context**
Stated dependencies for uwtools is Python >= 3.9.  Some people might use Python 3.9 or 3.10, which will not work.

**Detailed Description**
Remove call to `datetime.UTC` function which is an alias, introduced in Python 3.11, to `datetime.timezone.utc`. Calling `datetime.timezone.utc` maintains backward compatibility with older versions of Python.

**Possible Implementation**
See #488

**Comment by maddenp-noaa** [comment]
Thank you for this report. The pre-merge tests we run via GitHub Actions do exercise all supported Python versions but, unfortunately, there seems to be an error with the test script: The logs clearly show the tests under 3.9 and 3.10 failing due to this issue, but Actions did not halt and fail the test. I'll fix that first and then circle back to this issue, which we should have detected earlier.

**Comment by maddenp-noaa** [comment]
@christopherwharrop-noaa I pushed a commit to `main` that, I believe, fixes the testing issue that allowed this bug to go unnoticed. Can you please bring your branch/PR up-to-date with `main`? The CI tests will run again, and if they then pass then I think we can approve and merge #488.

**Comment by christopherwharrop-noaa** [comment]
@maddenp-noaa I rebased from main and pushed.  The tests seem to be passing now.

**Comment by maddenp-noaa** [comment]
@christopherwharrop-noaa This is merged onto `main` now, thanks for the fix. We're hoping to do a new release later this week or early next week, but if you're installing via `pip` directly from the repo, you should be good to go.

**Comment by christopherwharrop-noaa** [comment]
@maddenp-noaa - Wonderful!  I will be installing via `pip`, and will target specific releases.  Previous example that I shared of the pip command I was using installed from `main`, but I can replace that with, for example, `2.2.0`.  It will be my responsibility to keep up with uwtools versions on my end and it will be no problem for me to move to the new release once it is out.  For posterity, here is how I will be installing, using pip that was installed into a Spack environment:

```
pip install 'uwtools @ git+https://github.com/ufs-community/uwtools@2.2.0#subdirectory=src'
```
